version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: event_point_production
      MYSQL_USER: event_point
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    ports:
      - '3306:3306'
  app:
    build: .
    image: event_point
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      DB_HOST: db
      DB_NAME: event_point_production
      DB_USER: root
      DB_PASSWORD:
      COOKIE_NAME: '_event_point_session'
      API_BASE_URL: 'api/v1'
    ports:
      - '3500:3000'
    depends_on:
      - db
    links:
      - db
